# Generated by Django 5.2.6 on 2025-09-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0003_quizattempt_quizanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
    ]
