# Generated by Django 5.2.6 on 2025-09-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0004_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Quizzes'},
        ),
    ]
