# Generated by Django 5.2.6 on 2025-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizzes', '0005_alter_quiz_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Upload a cover image for this quiz (recommended size: 800x400px)', null=True, upload_to='quiz_covers/'),
        ),
    ]
